package auditlog_test

import (
	"testing"

	auditlog "github.com/larsartmann/samber-do-auditlog"
)

func TestRunID_AutoGeneratedWhenEmpty(t *testing.T) {
	t.Parallel()

	plugin, err := auditlog.New(auditlog.Config{
		Enabled: true,
	})
	if err != nil {
		t.Fatalf("New: %v", err)
	}

	report := plugin.Report()
	if report.RunID == "" {
		t.Error("expected auto-generated RunID, got empty")
	}

	if len(report.RunID) != 32 {
		t.Errorf("expected 32-char hex RunID, got %d chars: %q", len(report.RunID), report.RunID)
	}
}

func TestRunID_PreservedWhenProvided(t *testing.T) {
	t.Parallel()

	customRunID := auditlog.RunID("my-trace-id-123")

	plugin, err := auditlog.New(auditlog.Config{
		Enabled: true,
		RunID:   customRunID,
	})
	if err != nil {
		t.Fatalf("New: %v", err)
	}

	report := plugin.Report()
	if report.RunID != customRunID {
		t.Errorf("expected custom RunID %q, got %q", customRunID, report.RunID)
	}
}

func TestRunID_StampedOnEvents(t *testing.T) {
	t.Parallel()

	var capturedEvents []auditlog.Event

	plugin, err := auditlog.New(auditlog.Config{
		Enabled: true,
		RunID:   "test-run-123",
		OnEvent: func(e auditlog.Event) {
			capturedEvents = append(capturedEvents, e)
		},
	})
	if err != nil {
		t.Fatalf("New: %v", err)
	}

	report := plugin.Report()

	if report.RunID != "test-run-123" {
		t.Errorf("report RunID: want %q, got %q", "test-run-123", report.RunID)
	}

	for _, evt := range capturedEvents {
		if evt.RunID != "test-run-123" {
			t.Errorf("event RunID: want %q, got %q", "test-run-123", evt.RunID)
		}
	}
}
